apiVersion: v1
kind: Service
metadata:
  labels:
    app: main-service
  name: main-service
  namespace: my-application
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: main-service
  type: ClusterIP
